services:
  - type: web
  plan: free
  name: python-employee
  runtime: python
  repo: https://github.com/ErickW01/python-employee-project
  buildCommand: "pip install requirements.txt"
  startCommand: "python app.py"