on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install flake8-html
    - run: flake8 --format=html --htmldir=flake_reports/
    - uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: flake_reports/
