on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install flake8-html
    - run: flake8 --format=html --htmldir=flake_reports/
    - uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: flake_reports/
  build-img:
    runs-on: ubuntu-latest
    steps:
    - run: docker login --username erickw01 --password ${{secrets.GIT_DOCKER}} ghcr.io
    - run: docker build . -t https://ghcr.io/erickw01/employee-image:latest
    - run: docker push https://ghcr.io/erickw01/employee-image:latest

