on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

stages:
  - test

lint-test:
  image: python:3.8.0-slim
  stage: test
  before_script:
    - pip3 install flake8-html
  script:
    - flake8 --format=html --htmldir=flake_reports/
  artifacts:
    when: always
    paths:
      - flake_reports/
