on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install flake8-html
    - run: flake8 --format=html --htmldir=flake_reports/
    - uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: flake_reports/
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: pip3 install pytest-html
  #   - run: pip3 install python3-sqlalchemy
  #   - run: pytest --html=pytest_reports/pytest-report.html --self-contained-html
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: unit-report
  #       path: pytest-report.html/


jobs:
  build:
    runs-on: docker:latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t https://ghcr.io/ErickW01/python-employee-project