on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install flake8-html
    - run: flake8 --format=html --htmldir=flake_reports/
    - uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: flake_reports/
  docker-login-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: erickw01
          password:  ${{secrets.GIT_DOCKER}}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/erickw01/employee-image .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/erickw01/employee-tag:latest